### DISCUSSION TITLE
Using Alarm States to turn on Lights

### DISCUSSION THREAD

**Discussion by T3SSERACT2** [leikoilja/ha-google-home#307] [Q&A] [answered]
Hi,
I'm totally new to the world of Home Assistant automations and am wondering if there is a way for me to take the state outputted by this integration to trigger an automation to turn on lights either when the alarm is ringing or a few minutes before it.

 When I tested it, the sensor counts down to the alarm ringing but the state never actually changes to "ringing"
![agsdfsawetre](https://user-images.githubusercontent.com/76566427/129226218-407df64e-55c5-4fc0-8bd6-695bd596cdb6.PNG)

Any help would be appreciated

Thanks

**Comment by leikoilja** [comment, marked as answer]
Yes, it should be totally possible, @T3SSERACT2 :) 
I am running [this](https://community.home-assistant.io/t/wake-up-light-alarm-with-sunrise-effect/255193) automation blueprint with a config like that for example

```yaml
- id: '1616699223824'
  alias: Wake-up light alarm with sunrise effect
  description: ''
  use_blueprint:
    path: sbyx/wake-up-light-alarm-with-sunrise-effect.yaml
    input:
      manual_time: '7:00:00'
      light_entity: light.bedroom_lights
      timestamp_sensor: sensor.bedroom_speaker_alarms
      sunrise_duration: 20
      post_sunrise_actions:
      - scene: scene.active
```
where the `timestamp_sensor` is my Google Home alarm entity :)
