### ISSUE TITLE
Reuse master_token when the integration is reloaded.

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-google-home#130]
## Describe the bug

Reuse `master_token` when HA is restarted and the integration i reloaded. Right now we save the `master_token` in `ConfigEntry`, but we don't reuse it. This will fix issues where you can get logged out of your Google Account on other devices.

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
Latest
```

## Glocaltokens Version (Underlying package)

```text
Not relevant
```

## Logs

```text
Not relevant
```

## Debug log

```yaml
logger:
  default: debug
  logs:
    custom_components.google_home: debug
```

```text

Not relevant

```
