### ISSUE TITLE
Change attribute time_left to duration instead

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-google-home#52]
## Version of the custom_component

Latest master
## Configuration

```yaml
timers:
  - fire_time: 1614879264
    date_time_utc: '2021-03-04 17:34:24'
    local_time: '2021-03-04 18:34:24'
    time_left: '0:30:00'
device: Kitchen timers
integration: ha-google-home
friendly_name: Kitchen timers
icon: 'mdi:timer-sand'
```

## Describe the bug

`time_left` should be `duration` instead. It does not count down, so i think the name is misleading
